services:
  app:
    build:
      context: ./app
    container_name: app
    env_file:
      - ./app/.env
    environment:
      RABBITMQ_URL: amqp://ml_user:ml_password@rabbitmq:5672/
      RABBITMQ_QUEUE: ml_task_queue
    volumes:
      - ./app/source:/app/source
    depends_on:
      - database
      - rabbitmq
    networks:
      - ml-service-network

  ml-worker-1:
    build:
      context: ./app
    container_name: ml-worker-1
    command: python -m source.worker
    env_file:
      - ./app/.env
    environment:
      WORKER_ID: worker-1
      RABBITMQ_URL: amqp://ml_user:ml_password@rabbitmq:5672/
      RABBITMQ_QUEUE: ml_task_queue
    volumes:
      - ./app/source:/app/source
    depends_on:
      - database
      - rabbitmq
    networks:
      - ml-service-network

  ml-worker-2:
    build:
      context: ./app
    container_name: ml-worker-2
    command: python -m source.worker
    env_file:
      - ./app/.env
    environment:
      WORKER_ID: worker-2
      RABBITMQ_URL: amqp://ml_user:ml_password@rabbitmq:5672/
      RABBITMQ_QUEUE: ml_task_queue
    volumes:
      - ./app/source:/app/source
    depends_on:
      - database
      - rabbitmq
    networks:
      - ml-service-network

  web-proxy:
    build:
      context: ./web-proxy
    container_name: web-proxy
    depends_on:
      - app
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - ml-service-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ml_user
      RABBITMQ_DEFAULT_PASS: ml_password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
    networks:
      - ml-service-network

  database:
    image: postgres:16
    container_name: database
    environment:
      POSTGRES_DB: ml_service_db
      POSTGRES_USER: ml_user
      POSTGRES_PASSWORD: ml_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ml-service-network

volumes:
  rabbitmq_data:
  postgres_data:

networks:
  ml-service-network:
    driver: bridge
